"""add is_active column

Revision ID: f253dcad1a3f
Revises: 5da85f6151a0
Create Date: 2026-02-16 19:34:55.493212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f253dcad1a3f'
down_revision: Union[str, None] = '5da85f6151a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column(
    'is_active',
    sa.Boolean(),
    nullable=False,
    server_default=sa.true()
)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('tasks', 'is_subscribed')
    # ### end Alembic commands ###
